name: deploy

on:
  push:
    branches:
      - 'main'
    paths:
      - 'CMakeLists.txt'
      - 'scripts/*'
      - 'template/*'
      - '.github/workflows/*.yml'
  schedule:
    - cron: '0 18 * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        token: ${{ SECRETS.ACCESS_TOKEN }}

    - name: Setup python env
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Fetch user activities
      run: |
        sh ./scripts/fetch-contrib-status.sh $PAT 5 > contrib-status.json
        python ./scripts/parse-contrib-status.py contrib-status.json
      env:
        PAT: ${{ SECRETS.ACCESS_TOKEN }}

    - name: Generate profile
      run: |
        cmake -B build -S .
        sh ./scripts/commit.sh "chore: flush README.md template"

    - name: Flush profile template
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ SECRETS.GITHUB_TOKEN }}
        branch: ${{ github.ref }}

    - name: Install wakatime section
      uses: anmol098/waka-readme-stats@master
      with:
        WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
        GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        COMMIT_MESSAGE: "chore: inject wakatime stats"
        SYMBOL_VERSION: 2
        SHOW_COMMIT: True
        SHOW_LANGUAGE: True
        SHOW_LINES_OF_CODE: True
        SHOW_TOTAL_CODE_TIME: True
        SHOW_OS: False
        SHOW_EDITORS: False
        SHOW_PROJECTS: False
        SHOW_TIMEZONE: False
        SHOW_LOC_CHART: False
        SHOW_SHORT_INFO: False
        SHOW_DAYS_OF_WEEK: False
        SHOW_UPDATED_DATE: False
        SHOW_PROFILE_VIEWS: False
        SHOW_LANGUAGE_PER_REPO: False

    #- name: push
    #  uses: ad-m/github-push-action@master
    #  with:
    #    github_token: ${{ SECRETS.GITHUB_TOKEN }}
    #    branch: ${{ github.ref }}
