name: deploy

on:
  push:
    branches:
      - 'main'
    paths:
      - 'CMakeLists.txt'
      - 'requirements.txt'
      - 'scripts/*'
      - 'snippet/*'
      - 'template/*'
      - '.github/workflows/*.yml'
  schedule:
    - cron: '0 18 * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        token: ${{ SECRETS.ACCESS_TOKEN }}

    - name: Setup python env
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install python dependencis
      run: |
        pip install -r requirements.txt

    - name: Generate profile
      run: |
        cmake -B build -S .
        sh ./scripts/commit.sh "chore: flush README.md template"

    - name: Post Generate profile
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ SECRETS.GITHUB_TOKEN }}
        branch: ${{ github.ref }}

    - name: Inject wakatime stats
      uses: anmol098/waka-readme-stats@master
      with:
        WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
        GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        COMMIT_MESSAGE: "chore: inject wakatime stats"
        SYMBOL_VERSION: 2
        SHOW_COMMIT: True
        SHOW_LANGUAGE: True
        SHOW_TOTAL_CODE_TIME: True
        SHOW_OS: False
        SHOW_EDITORS: False
        SHOW_PROJECTS: False
        SHOW_TIMEZONE: False
        SHOW_LOC_CHART: False
        SHOW_SHORT_INFO: False
        SHOW_DAYS_OF_WEEK: False
        SHOW_UPDATED_DATE: False
        SHOW_PROFILE_VIEWS: False
        SHOW_LINES_OF_CODE: False
        SHOW_LANGUAGE_PER_REPO: False

    - name: Generate snippets
      run: |
        python ./snippet/wip-repos.py $PAT 5
      env:
        PAT: ${{ SECRETS.ACCESS_TOKEN }}

    - name: Apply snippets
      run: |
        python ./scripts/apply-snippets.py light
        cmake --build build --target apply-snippets
        sh ./scripts/commit.sh "chore: apply snippets"

    - name: Finalize deployment
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ SECRETS.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
